FROM node:24-alpine AS deps

WORKDIR /deps

COPY package*.json ./

RUN npm ci



FROM node:24-alpine AS build

WORKDIR /app

COPY --from=deps /deps/node_modules ./node_modules

COPY . .

RUN npm run build



FROM nginx:alpine AS production


ARG BUILD_DATE
ARG VERSION
ARG NODE_ENV=production

LABEL org.opencontainers.image.created=$BUILD_DATE
LABEL org.opencontainers.image.version=$VERSION
LABEL org.opencontainers.image.title="lab4-frontend"


COPY ./default.conf ./etc/nginx/conf.d/default.conf

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=5s \
    CMD wget -qO- http://localhost/ || exit 1

